#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm for GUI clients like GitKraken that don't use interactive shell
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Run type checking first
npm run types:check

# Run lint-staged for linting and formatting
npx lint-staged
